name: Run PlatformIO Tests

on:
  push:
    branches:
      - master
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install PlatformIO
      run: |
        pip install platformio

    - name: Set Environment MBEDTLS_VERSION_MAJOR Variable
      run: echo "MBEDTLS_VERSION_MAJOR=3" >> $GITHUB_ENV

    - name: Run tests - First Batch
      run: pio test -e native -vvv

    - name: Set Environment MBEDTLS_BACKPORT Variable
      run: echo "MBEDTLS_BACKPORT=true" >> $GITHUB_ENV

    - name: Run tests - Second Batch
      run: pio test -e native -vvv
