name: Issue Checker

on:
  issues:
    types: [opened]

jobs:
  check-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Required Information
        uses: actions/github-script@v4
        with:
          script: |
            const { issue } = context.payload;
            const requiredFields = ['Description', 'Steps to Reproduce', 'Expected Behavior', 'Actual Behavior', 'Environment'];
            let missingFields = requiredFields.filter(field => !issue.body.includes(`### ${field}`));
            if (missingFields.length > 0) {
              const commentBody = `The following fields are missing: ${missingFields.join(', ')}`;
              await github.issues.createComment({
                ...context.repo,
                issue_number: issue.number,
                body: commentBody
              });
              await github.issues.update({
                ...context.repo,
                issue_number: issue.number,
                state: 'closed'
              });
            }
